[project]
type = "library"
name = "Core"
version = "0.1.0"
license = "ISC"
description = "The Flare core library."
url = "https://flare-lang.org"
url-doc = "https://flare-lang.org/documentation.html"
url-src = "https://github.com/flare-lang/flare/tree/master/src/core"

[lints]
undocumented_declaration = "error"
